version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ./.env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: samiel19/foodgram_backend
    env_file: ./.env
    restart: always
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
  frontend:
    image: samiel19/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend
