# Generated by Django 3.2.16 on 2023-06-26 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(db_index=True, help_text='Юзернейм', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid_username', message='Имя пользователя должно состоять из букв и цифр', regex='^[\\w.@+-]+$')], verbose_name='Уникальный юзернейм'),
        ),
    ]
