# Generated by Django 3.2.16 on 2023-06-21 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230620_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.CharField(help_text='Пароль необходим!', max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(help_text='Юзернейм', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid_username', message='Username must be Alphanumeric', regex='^[\\w.@+-]+$')], verbose_name='Уникальный юзернейм'),
        ),
    ]
