# Generated by Django 3.2.16 on 2023-06-26 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20230623_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-created_at',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Меньше минуты - не рецепт!')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Тэг'),
        ),
    ]
