# Generated by Django 3.2.16 on 2023-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=64, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='recipy',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='recipy',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=64, unique=True, verbose_name='Слаг'),
        ),
    ]
